version: 2.1
executors:
  python_docker:
    docker:
      - image: circleci/python:3.7-node-browsers-legacy
jobs:
  build:
    executor: python_docker
    steps:
      - checkout:
          path: ~/project
      - run:
          command: |
            ls -al
            sudo chown -R circleci:circleci .
            chmod -R +rwx ./ci
            ./ci/setup.sh
            echo 'Hello world'
          name: setup

workflows:
  build_test_and_deploy:
    jobs:
      - build:
          name: build
